import { resizeImage } from '@starter-kit/utils/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Clock, MessageCircle, Heart, Calendar } from 'lucide-react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import { Avatar, AvatarFallback, AvatarImage } from '../components/ui/avatar';
import { Badge } from '../components/ui/badge';
import { ReadingProgress } from '../components/blog/ReadingProgress';
import { TableOfContents } from '../components/blog/TableOfContents';
import { AuthorBio } from '../components/blog/AuthorBio';
import { ShareButtons } from '../components/blog/ShareButtons';
import {
	PageByPublicationDocument,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
};

type Props = PostProps | PageProps;

const Post = ({ publication, post }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	useEmbeds({ enabled: canLoadEmbeds });
	const tagsList = (post.tags ?? []).map((tag) => (
		<li key={tag.id}>
			<Link
				href={`/tag/${tag.slug}`}
				className="block rounded-full border px-2 py-1 font-medium hover:bg-slate-50 dark:border-neutral-800 dark:hover:bg-neutral-800 md:px-4"
			>
				#{tag.slug}
			</Link>
		</li>
	));

	if (post.hasLatexInPost) {
		setTimeout(() => {
			handleMathJax(true);
		}, 500);
	}

	useEffect(() => {
		if (screen.width <= 425) {
			setMobMount(true);
		}

		if (!post) {
			return;
		}

		// TODO:
		// More of an alert, did this below to wrap async funcs inside useEffect
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, [post]);

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, {
				w: 1600,
				h: 840,
				c: 'thumb',
		  })
		: undefined;

	return (
		<>
			<ReadingProgress />
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>

			{/* Hero Section */}
			<div className="relative">
				{coverImageSrc && (
					<div className="relative h-[500px] w-full">
						<Image
							src={coverImageSrc}
							alt={post.title}
							fill
							className="object-cover"
							priority
						/>
						<div className="absolute inset-0 bg-gradient-to-t from-black via-black/70 to-transparent" />
					</div>
				)}

				<div className={`${coverImageSrc ? 'absolute bottom-0 left-0 right-0' : 'relative'} px-4 sm:px-6 lg:px-8 pb-12`}>
					<Container className="mx-auto max-w-4xl">
						<motion.div
							initial={{ opacity: 0, y: 30 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.6 }}
						>
							{/* Tags */}
							{post.tags && post.tags.length > 0 && (
								<div className="flex gap-2 mb-4 flex-wrap">
									{post.tags.slice(0, 3).map((tag) => (
										<Link key={tag.id} href={`/tag/${tag.slug}`}>
											<Badge variant="secondary" className="bg-blue-500/20 text-blue-300 border-blue-400/30 hover:bg-blue-500/30">
												{tag.name}
											</Badge>
										</Link>
									))}
								</div>
							)}

							{/* Title */}
							<h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
								{post.title}
							</h1>

							{/* Subtitle */}
							{post.subtitle && (
								<p className="text-xl text-white/80 mb-6 leading-relaxed">
									{post.subtitle}
								</p>
							)}

							{/* Author and Meta */}
							<div className="flex items-center gap-6 flex-wrap">
								<div className="flex items-center gap-3">
									<Avatar className="h-12 w-12 border-2 border-white/20">
										<AvatarImage src={post.author.profilePicture || ''} alt={post.author.name} />
										<AvatarFallback className="bg-blue-500/20 text-blue-300">
											{post.author.name.charAt(0)}
										</AvatarFallback>
									</Avatar>
									<div>
										<div className="text-white font-medium">{post.author.name}</div>
										<div className="text-white/60 text-sm">@{post.author.username}</div>
									</div>
								</div>

								<div className="flex items-center gap-4 text-white/70 text-sm flex-wrap">
									<div className="flex items-center gap-1.5">
										<Calendar className="w-4 h-4" />
										<DateFormatter dateString={post.publishedAt} />
									</div>
									<div className="flex items-center gap-1.5">
										<Clock className="w-4 h-4" />
										<span>{post.readTimeInMinutes} min read</span>
									</div>
									<div className="flex items-center gap-1.5">
										<Heart className="w-4 h-4" />
										<span>{post.reactionCount}</span>
									</div>
									<div className="flex items-center gap-1.5">
										<MessageCircle className="w-4 h-4" />
										<span>{post.comments.totalDocuments}</span>
									</div>
								</div>

								<div className="ml-auto">
									<ShareButtons url={post.url} title={post.title} />
								</div>
							</div>
						</motion.div>
					</Container>
				</div>
			</div>

			{/* Content Section */}
		<Container className="mx-auto max-w-screen-2xl px-4 sm:px-6 lg:px-8 py-12">
			<div className={`grid grid-cols-1 gap-12 ${post.features.tableOfContents.isEnabled && post.features.tableOfContents.items.length > 0 ? 'lg:grid-cols-12' : ''}`}>
				{/* Main Content */}
				<motion.article
					initial={{ opacity: 0, y: 20 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.6, delay: 0.2 }}
					className={post.features.tableOfContents.isEnabled && post.features.tableOfContents.items.length > 0 ? 'lg:col-span-8' : ''}
				>
					<div className="prose prose-invert prose-lg max-w-none">
						<MarkdownToHtml contentMarkdown={post.content.markdown} />
					</div>

					{/* Tags Section */}
					{(post.tags ?? []).length > 0 && (
						<div className="mt-12 pt-8 border-t border-white/10">
							<h3 className="text-lg font-semibold text-white mb-4">Tagged with</h3>
							<div className="flex flex-wrap gap-2">
								{post.tags!.map((tag) => (
									<Link key={tag.id} href={`/tag/${tag.slug}`}>
										<Badge variant="outline" className="border-white/20 text-white/80 hover:bg-white/10">
											#{tag.slug}
										</Badge>
									</Link>
								))}
							</div>
						</div>
					)}

					{/* Author Bio */}
					<div className="mt-12">
						<AuthorBio
							name={post.author.name}
							username={post.author.username}
							profilePicture={post.author.profilePicture}
						/>
					</div>
				</motion.article>

				{/* Sidebar */}
				{post.features.tableOfContents.isEnabled && post.features.tableOfContents.items.length > 0 && (
					<aside className="lg:col-span-4">
						<TableOfContents items={post.features.tableOfContents.items} />
					</aside>
				)}
			</div>
		</Container>
		</>
	);
};

const Page = ({ page }: PageProps) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<MarkdownToHtml contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage}>
			<Layout>
				<Container className="mx-auto flex max-w-3xl flex-col items-stretch gap-10 px-5 py-10">
					<article className="flex flex-col items-start gap-10 pb-10">
						{props.type === 'post' && <Post {...props} />}
						{props.type === 'page' && <Page {...props} />}
					</article>
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		return {
			props: {
				type: 'post',
				post: postData.publication.post,
				publication: postData.publication,
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => {
			return {
				params: {
					slug: slug,
				},
			};
		}),
		fallback: 'blocking',
	};
}
