import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { SEO_CONFIG } from '../lib/seo-config';
import { useEffect, useState } from 'react';
import { Waypoint } from 'react-waypoint';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, FileText, Clock, MessageCircle, User } from 'lucide-react';
import Image from 'next/image';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { FloatingElement } from '../components/ui/FloatingElement';
import { Avatar, AvatarFallback, AvatarImage } from '../components/ui/avatar';
import { Badge } from '../components/ui/badge';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);
	const [isMobile, setIsMobile] = useState(false);

	useEffect(() => {
		const checkMobile = () => {
			setIsMobile(window.innerWidth < 768);
		};
		checkMobile();
		window.addEventListener("resize", checkMobile);
		return () => window.removeEventListener("resize", checkMobile);
	}, []);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};

	const containerVariants = {
		hidden: { opacity: 0 },
		visible: {
			opacity: 1,
			transition: { staggerChildren: 0.15, delayChildren: 0.3 },
		},
	};

	const heroVariants = {
		hidden: { opacity: 0 },
		visible: {
			opacity: 1,
			transition: { staggerChildren: 0.2, delayChildren: 0.5 },
		},
	};

	const fadeInUpVariants = {
		hidden: { y: 60, opacity: 0, filter: "blur(10px)", scale: 0.9 },
		visible: {
			y: 0,
			opacity: 1,
			filter: "blur(0px)",
			scale: 1,
			transition: { duration: 0.8, ease: [0.25, 0.46, 0.45, 0.94] as any },
		},
	};

	return (
		<AppProvider publication={publication}>
			<Layout>
					<Head>
					<title>{SEO_CONFIG.site.title} | Social Commerce Insights & Updates</title>
					<meta name="description" content={SEO_CONFIG.site.description} />
					<link rel="canonical" href={SEO_CONFIG.site.url} />
					
					{/* Open Graph / Facebook */}
					<meta property="og:type" content={SEO_CONFIG.openGraph.type} />
					<meta property="og:url" content={SEO_CONFIG.site.url} />
					<meta property="og:site_name" content={SEO_CONFIG.openGraph.siteName} />
					<meta property="og:title" content={`${SEO_CONFIG.site.title} | Social Commerce Insights & Updates`} />
					<meta property="og:description" content={SEO_CONFIG.site.description} />
					<meta property="og:image" content={publication.ogMetaData?.image || `${SEO_CONFIG.site.baseUrl}${SEO_CONFIG.assets.ogImageDefault}`} />
					<meta property="og:image:width" content={SEO_CONFIG.openGraph.imageWidth.toString()} />
					<meta property="og:image:height" content={SEO_CONFIG.openGraph.imageHeight.toString()} />
					<meta property="og:locale" content={SEO_CONFIG.openGraph.locale} />
					
					{/* Twitter */}
					<meta name="twitter:card" content={SEO_CONFIG.twitter.card} />
					<meta name="twitter:url" content={SEO_CONFIG.site.url} />
					<meta name="twitter:title" content={`${SEO_CONFIG.site.title} | Social Commerce Insights & Updates`} />
					<meta name="twitter:description" content={SEO_CONFIG.site.description} />
					<meta name="twitter:image" content={publication.ogMetaData?.image || `${SEO_CONFIG.site.baseUrl}${SEO_CONFIG.assets.ogImageDefault}`} />
					<meta name="twitter:site" content={SEO_CONFIG.twitter.site} />
					<meta name="twitter:creator" content={SEO_CONFIG.twitter.creator} />
					
					{/* Additional Meta Tags */}
					<meta name="keywords" content={SEO_CONFIG.meta.keywords.join(', ')} />
					<meta name="author" content={SEO_CONFIG.defaultAuthor.name} />
					<meta name="theme-color" content={SEO_CONFIG.meta.themeColor} />
					<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
					
					{/* Structured Data */}
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication, SEO_CONFIG)),
						}}
					/>
				</Head>

				<div className="relative z-10 w-full">
					{/* Hero Section */}
					<section className="min-h-[60vh] flex items-center justify-center px-4 sm:px-6 lg:px-8">
						<motion.div
							variants={heroVariants}
							initial="hidden"
							animate="visible"
							className="w-full max-w-4xl mx-auto text-center"
						>
							<div className="space-y-6 sm:space-y-8 pt-10 sm:pt-20">
								{/* Badge */}
								<motion.div
									variants={fadeInUpVariants}
									whileHover={{
										scale: isMobile ? 1 : 1.05,
										rotate: isMobile ? 0 : 2,
									}}
									className="inline-flex items-center gap-2 bg-black/20 backdrop-blur-md border border-white/10 rounded-full px-4 py-2 shadow-lg"
								>
									<motion.span
										animate={{ rotate: [0, 10, -10, 0] }}
										transition={{
											duration: 2,
											repeat: Number.POSITIVE_INFINITY,
											delay: 1,
										}}
										className="text-xl"
									>
										✨
									</motion.span>
									<span className="text-white/80 text-sm font-medium">
										Community & Updates
									</span>
								</motion.div>

								{/* Main Title */}
								<motion.h1
									variants={fadeInUpVariants}
									className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold !leading-tight"
								>
									<motion.span
										initial={{ opacity: 0, y: 30 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ delay: 1.2, duration: 0.8 }}
										className="block text-white mb-2"
									>
										The Shopsical
									</motion.span>
									<motion.span
										initial={{ opacity: 0, y: 30 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ delay: 1.4, duration: 0.8 }}
										className="block bg-gradient-to-r from-blue-400 to-primary bg-clip-text text-transparent"
									>
										Blog
									</motion.span>
								</motion.h1>

								{/* Subtitle */}
								<motion.p
									variants={fadeInUpVariants}
									className="text-white/80 text-lg sm:text-xl max-w-3xl mx-auto leading-relaxed"
								>
									<motion.span
										initial={{ opacity: 0 }}
										animate={{ opacity: 1 }}
										transition={{ delay: 1.8, duration: 0.8 }}
									>
										Discover the latest trends, styling tips, and updates from the Shopsical team.
										Explore our stories and join the conversation.
									</motion.span>
								</motion.p>
							</div>
						</motion.div>
					</section>

			{/* Featured Post Section */}
			{posts.length > 0 && (
				<section className="py-8 px-4 sm:px-6 lg:px-8">
					<div className="max-w-6xl mx-auto">
						<motion.div
							initial={{ opacity: 0, y: 30 }}
							whileInView={{ opacity: 1, y: 0 }}
							viewport={{ once: true }}
							transition={{ duration: 0.6 }}
						>
							<Link href={`/${posts[0].slug}`} className="block group">
								<div className="relative overflow-hidden rounded-3xl bg-black/20 backdrop-blur-md border border-white/10 hover:border-blue-400/30 transition-all duration-500">
									{/* Cover Image */}
									{posts[0].coverImage?.url && (
										<div className="relative h-[400px] sm:h-[500px] overflow-hidden">
											<Image
												src={posts[0].coverImage.url}
												alt={posts[0].title}
												fill
												className="object-cover group-hover:scale-105 transition-transform duration-700"
												priority
											/>
											<div className="absolute inset-0 bg-gradient-to-t from-black via-black/50 to-transparent" />
										</div>
									)}
									
									{/* Content Overlay */}
									<div className={`${posts[0].coverImage?.url ? 'absolute bottom-0 left-0 right-0' : 'relative'} p-8 sm:p-12`}>
										<div className="flex items-center gap-3 mb-4">
											<Badge variant="secondary" className="bg-blue-500/20 text-blue-300 border-blue-400/30 hover:bg-blue-500/30">
												Featured Post
											</Badge>
											{posts[0].tags && posts[0].tags.length > 0 && (
												<Badge variant="outline" className="border-white/20 text-white/80 hover:bg-white/10">
													{posts[0].tags[0].name}
												</Badge>
											)}
										</div>

										<h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white mb-4 group-hover:text-blue-200 transition-colors duration-300">
											{posts[0].title}
										</h2>

										<p className="text-white/80 text-lg mb-6 line-clamp-2 max-w-3xl">
											{posts[0].brief}
										</p>

										{/* Author and Meta */}
										<div className="flex items-center gap-6 flex-wrap">
											<div className="flex items-center gap-3">
												<Avatar className="h-10 w-10 border-2 border-white/20">
													<AvatarImage src={posts[0].author.profilePicture || ''} alt={posts[0].author.name} />
													<AvatarFallback className="bg-blue-500/20 text-blue-300">
														{posts[0].author.name.charAt(0)}
													</AvatarFallback>
												</Avatar>
												<span className="text-white/90 font-medium">{posts[0].author.name}</span>
											</div>

											<div className="flex items-center gap-4 text-white/60 text-sm">
												<div className="flex items-center gap-1.5">
													<Clock className="w-4 h-4" />
													<span>{posts[0].readTimeInMinutes} min read</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</Link>
						</motion.div>
					</div>
				</section>
			)}

			{/* Posts Grid Section */}
			<section className="py-16 px-4 sm:px-6 lg:px-8">
				<div className="max-w-6xl mx-auto">
					{posts.length > 1 && (
						<>
							<motion.h2
								initial={{ opacity: 0, y: 20 }}
								whileInView={{ opacity: 1, y: 0 }}
								viewport={{ once: true }}
								className="text-2xl sm:text-3xl font-bold text-white mb-8"
							>
								More Stories
							</motion.h2>

							<motion.div
								initial="hidden"
								whileInView="visible"
								viewport={{ once: true, amount: 0.1 }}
								variants={containerVariants}
								className="grid grid-cols-1 md:grid-cols-2 gap-8"
							>
								{posts.slice(1).map((post, index) => (
									<motion.div
										key={post.id}
										variants={fadeInUpVariants}
										whileHover={{ scale: 1.02, y: -5 }}
										className="group"
									>
										<Link href={`/${post.slug}`} className="block h-full">
											<div className="bg-black/20 backdrop-blur-md border border-white/10 rounded-2xl overflow-hidden h-full flex flex-col hover:bg-black/30 hover:border-blue-400/30 transition-all duration-300 group-hover:shadow-xl group-hover:shadow-blue-400/10">
												{/* Cover Image */}
												{post.coverImage?.url && (
													<div className="relative h-48 overflow-hidden">
														<Image
															src={post.coverImage.url}
															alt={post.title}
															fill
															className="object-cover group-hover:scale-110 transition-transform duration-500"
														/>
													</div>
												)}

												<div className="p-6 flex flex-col flex-grow">
													{/* Tags */}
													{post.tags && post.tags.length > 0 && (
														<div className="flex gap-2 mb-3 flex-wrap">
															{post.tags.slice(0, 2).map((tag) => (
																<Badge
																	key={tag.id}
																	variant="outline"
																	className="border-white/20 text-white/70 text-xs hover:bg-white/10"
																>
																	{tag.name}
																</Badge>
															))}
														</div>
													)}

													<h3 className="text-xl sm:text-2xl font-semibold mb-3 text-white group-hover:text-blue-200 transition-colors duration-300 line-clamp-2">
														{post.title}
													</h3>

													<p className="text-white/70 mb-4 leading-relaxed group-hover:text-white/80 transition-colors duration-300 line-clamp-2 flex-grow">
														{post.brief}
													</p>

													{/* Author and Meta */}
													<div className="flex items-center justify-between mt-auto pt-4 border-t border-white/10">
														<div className="flex items-center gap-2">
															<Avatar className="h-8 w-8 border border-white/20">
																<AvatarImage src={post.author.profilePicture || ''} alt={post.author.name} />
																<AvatarFallback className="bg-blue-500/20 text-blue-300 text-xs">
																	{post.author.name.charAt(0)}
																</AvatarFallback>
															</Avatar>
															<span className="text-white/80 text-sm">{post.author.name}</span>
														</div>

														<div className="flex items-center gap-3 text-white/50 text-xs">
															<div className="flex items-center gap-1">
																<Clock className="w-3.5 h-3.5" />
																<span>{post.readTimeInMinutes}m</span>
															</div>
														</div>
													</div>
												</div>
											</div>
										</Link>
									</motion.div>
								))}
							</motion.div>
						</>
					)}

					{/* Load More Button */}
					{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<div className="mt-16 text-center">
							<button
								onClick={loadMore}
								className="inline-flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white px-8 py-4 rounded-full transition-all duration-300 backdrop-blur-md border border-white/10"
							>
								<span>Load More Stories</span>
								<ArrowRight className="w-4 h-4" />
							</button>
						</div>
					)}
					{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
					)}
				</div>
			</section>
				</div>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
