import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Waypoint } from 'react-waypoint';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, FileText } from 'lucide-react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { FloatingElement } from '../components/ui/FloatingElement';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);
	const [isMobile, setIsMobile] = useState(false);

	useEffect(() => {
		const checkMobile = () => {
			setIsMobile(window.innerWidth < 768);
		};
		checkMobile();
		window.addEventListener("resize", checkMobile);
		return () => window.removeEventListener("resize", checkMobile);
	}, []);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};

	const containerVariants = {
		hidden: { opacity: 0 },
		visible: {
			opacity: 1,
			transition: { staggerChildren: 0.15, delayChildren: 0.3 },
		},
	};

	const heroVariants = {
		hidden: { opacity: 0 },
		visible: {
			opacity: 1,
			transition: { staggerChildren: 0.2, delayChildren: 0.5 },
		},
	};

	const fadeInUpVariants = {
		hidden: { y: 60, opacity: 0, filter: "blur(10px)", scale: 0.9 },
		visible: {
			y: 0,
			opacity: 1,
			filter: "blur(0px)",
			scale: 1,
			transition: { duration: 0.8, ease: [0.25, 0.46, 0.45, 0.94] as any },
		},
	};

	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>

				<div className="relative z-10 w-full">
					{/* Hero Section */}
					<section className="min-h-[60vh] flex items-center justify-center px-4 sm:px-6 lg:px-8">
						<motion.div
							variants={heroVariants}
							initial="hidden"
							animate="visible"
							className="w-full max-w-4xl mx-auto text-center"
						>
							<div className="space-y-6 sm:space-y-8 pt-10 sm:pt-20">
								{/* Badge */}
								<motion.div
									variants={fadeInUpVariants}
									whileHover={{
										scale: isMobile ? 1 : 1.05,
										rotate: isMobile ? 0 : 2,
									}}
									className="inline-flex items-center gap-2 bg-black/20 backdrop-blur-md border border-white/10 rounded-full px-4 py-2 shadow-lg"
								>
									<motion.span
										animate={{ rotate: [0, 10, -10, 0] }}
										transition={{
											duration: 2,
											repeat: Number.POSITIVE_INFINITY,
											delay: 1,
										}}
										className="text-xl"
									>
										✨
									</motion.span>
									<span className="text-white/80 text-sm font-medium">
										Community & Updates
									</span>
								</motion.div>

								{/* Main Title */}
								<motion.h1
									variants={fadeInUpVariants}
									className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold !leading-tight"
								>
									<motion.span
										initial={{ opacity: 0, y: 30 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ delay: 1.2, duration: 0.8 }}
										className="block text-white mb-2"
									>
										The Shopsical
									</motion.span>
									<motion.span
										initial={{ opacity: 0, y: 30 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ delay: 1.4, duration: 0.8 }}
										className="block bg-gradient-to-r from-blue-400 to-primary bg-clip-text text-transparent"
									>
										Blog
									</motion.span>
								</motion.h1>

								{/* Subtitle */}
								<motion.p
									variants={fadeInUpVariants}
									className="text-white/80 text-lg sm:text-xl max-w-3xl mx-auto leading-relaxed"
								>
									<motion.span
										initial={{ opacity: 0 }}
										animate={{ opacity: 1 }}
										transition={{ delay: 1.8, duration: 0.8 }}
									>
										Discover the latest trends, styling tips, and updates from the Shopsical team.
										Explore our stories and join the conversation.
									</motion.span>
								</motion.p>
							</div>
						</motion.div>
					</section>

					{/* Posts Grid Section */}
					<section className="py-16 px-4 sm:px-6 lg:px-8">
						<div className="max-w-6xl mx-auto">
							<motion.div
								initial="hidden"
								whileInView="visible"
								viewport={{ once: true, amount: 0.1 }}
								variants={containerVariants}
								className="grid grid-cols-1 md:grid-cols-2 gap-8"
							>
								{posts.map((post, index) => (
									<motion.div
										key={post.id}
										variants={fadeInUpVariants}
										whileHover={{ scale: 1.02, y: -5 }}
										className="group"
									>
										<Link href={`/${post.slug}`} className="block h-full">
											<div className="bg-black/20 backdrop-blur-md border border-white/10 rounded-2xl p-8 h-full flex flex-col hover:bg-black/30 hover:border-blue-400/30 transition-all duration-300 group-hover:shadow-xl group-hover:shadow-blue-400/10">
												<FloatingElement
													amplitude={3}
													duration={4 + (index % 3)}
													delay={index * 0.2}
												>
													<div className="mb-6 p-4 bg-white/5 inline-block rounded-xl text-blue-400 group-hover:text-blue-300 transition-colors duration-300">
														<FileText className="w-8 h-8" />
													</div>
												</FloatingElement>

												<h3 className="text-xl sm:text-2xl font-semibold mb-4 text-white group-hover:text-blue-200 transition-colors duration-300 line-clamp-2">
													{post.title}
												</h3>

												<p className="text-white/70 mb-6 leading-relaxed group-hover:text-white/80 transition-colors duration-300 line-clamp-3 flex-grow">
													{post.brief}
												</p>

												<div className="flex items-center justify-between mt-auto">
													{/* <div className="flex items-center gap-2 text-sm text-white/50">
														<span>{new Date(post.publishedAt).toLocaleDateString()}</span>
														<span>•</span>
														<span>{post.readTimeInMinutes} min read</span>
													</div> */}

													<div className="flex items-center gap-2 text-blue-400 group-hover:text-blue-300 transition-colors duration-300">
														<span className="text-sm font-medium">Read Article</span>
														<ArrowRight className="w-4 h-4 transform group-hover:translate-x-1 transition-transform duration-300" />
													</div>
												</div>
											</div>
										</Link>
									</motion.div>
								))}
							</motion.div>

							{/* Load More Button */}
							{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
								<div className="mt-16 text-center">
									<button
										onClick={loadMore}
										className="inline-flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white px-8 py-4 rounded-full transition-all duration-300 backdrop-blur-md border border-white/10"
									>
										<span>Load More Stories</span>
										<ArrowRight className="w-4 h-4" />
									</button>
								</div>
							)}
							{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
								<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
							)}
						</div>
					</section>
				</div>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
